NUM_LANES = 4

FRAME_WIDTH = 320
FRAME_HEIGHT = 240

MIN_VEHICLE_AREA = 1200
MAX_VEHICLE_AREA = 80000

BASE_GREEN_TIME = 10
MAX_GREEN_TIME = 60
MIN_GREEN_TIME = 5
YELLOW_TIME = 3
VEHICLES_PER_SECOND = 0.5

CONGESTION_THRESHOLD = 10
HIGH_CONGESTION_THRESHOLD = 20

VIDEO_SOURCES = [
    "videos/lane1.mp4",
    "videos/lane2.mp4",
    "videos/lane3.mp4",
    "videos/lane4.mp4",
]
